#!/usr/bin/env python3

from sys import argv
import requests
import os

shame = False

def usage():
    print('Usage: "./gitbuildcheck user/repository", "./gitbuildcheck user/repository --shame", "./gitbuildcheck --shame user/repository"')

if len(argv) != 2 and len(argv) != 3:
    usage()
    exit(1)

if len(argv) == 3:
    if argv[1] == '--shame' or argv[2] == '--shame':
        shame = True
    else:
        usage()
        exit(1)
    
    if '/' in argv[1]:
        usr, repo = argv[1].split('/')
    elif '/' in argv[2]:
        usr, repo = argv[2].split('/')
    else:
        usage()
        exit(1)

if len(argv) == 2:
    if '/' in argv[1]:
        usr, repo = argv[1].split('/')
    else:
        usage()
        exit(1)

website = 'https://github.com/' + usr + '/'+ repo + '/actions/workflows/python-app.yml/badge.svg'

res = requests.get(website)
if 'failing' in res.text:
    if shame == True:
        os.system('./runsiren.sh')
    exit(1)

elif 'passing' in res.text:
    exit(0)

else:
    if shame == True:
        os.system('./runsiren.sh')
    print('Repository not found')
    exit(1)

        
